### ISSUE TITLE
Unable to start NOde JS server

### ISSUE THREAD

**Issue by gattur** [airavata-courses/Gateway-Falcons#15]
> node ./bin/www
path.js:39
    throw new ERR_INVALID_ARG_TYPE('path', 'string', path);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.join (path.js:432:7)
    at parseFile (D:\sander\gateway-falcons\back-end\server-data-ms\utils\json_fileparser.js:4:27)
    at Object.<anonymous> (D:\sander\gateway-falcons\back-end\server-data-ms\app.js:28:26)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (D:\sander\gateway-falcons\back-end\server-data-ms\bin\www:7:11)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! server-data-ms@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1

**Comment by tylerthedeveloper** [comment]
We've addressed this with the necessary configuration files. This is due to not having the folder and appropriate config and environment files that were securely distributed to you. Given inactivity and the clarification, I am closing this issue.
