### ISSUE TITLE
unable to start front end. So was not able to test the application.

### ISSUE THREAD

**Issue by arswaroop** [airavata-courses/Gateway-Falcons#16]
Npm start on front end is giving below error- 
PS C:\Code\gateway-falcons\front-end\app> npm start
_____________________________________________________
> app@0.1.0 start C:\Code\gateway-falcons\front-end\app
> react-scripts start

'react-scripts' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! app@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the app@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\arswa\AppData\Roaming\npm-cache\_logs\2019-02-07T04_37_58_669Z-debug.log
_____________________________________________________________

**Comment by arswaroop** [comment]
was able to install the component but got another error-

c:\Code\gateway-falcons\front-end\app>npm start

> app@0.1.0 start c:\Code\gateway-falcons\front-end\app
> react-scripts start

c:\Code\gateway-falcons\front-end\app\node_modules\ajv\lib\keyword.js:65
      throw new Error('custom keyword definition is invalid: '  + this.errorsText(validateDefinition.errors));
      ^

Error: custom keyword definition is invalid: data.errors should be boolean
    at Ajv.addKeyword (c:\Code\gateway-falcons\front-end\app\node_modules\ajv\lib\keyword.js:65:13)
    at module.exports (c:\Code\gateway-falcons\front-end\app\node_modules\ajv-errors\index.js:10:7)
    at Object.<anonymous> (c:\Code\gateway-falcons\front-end\app\node_modules\schema-utils\src\validateOptions.js:22:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)

You guys have any suggestion?

**Comment by Chirag-Galani** [comment]
Perform the following steps and let us respond: 
npm uninstall ajv
npm install ajv@6.8.1

**Comment by arswaroop** [comment]
That worked!
