### ISSUE TITLE
Unable to create env in diet service

### ISSUE THREAD

**Issue by gattur** [airavata-courses/Gateway-Falcons#19]
$ python -m virtualenv env
Using base prefix 'C:\\Users\\R\\AppData\\Local\\Programs\\Python\\Python37-32'
New python executable in D:\sander\gateway-falcons\diet-service\diet\env\Scripts\python.exe
Installing setuptools, pip, wheel...
done.

R@LAPTOP-L MINGW64 /d/sander/gateway-falcons/diet-service/diet (diet-service)
$ source env/bin/activate
bash: env/bin/activate: No such file or directory

C:\Users\R>python
Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

Can you help if something is wrong with my env setup

**Comment by Praneta-Paithankar** [comment]
Hi,

Instead of `source env/bin/activate`, could you try using  `env\Scripts\activate` ? This instruction is for  Linux system.

You can refer [https://pymote.readthedocs.io/en/latest/install/windows_virtualenv.html](Link) for creating and activating the virtual environment on windows. Let me know if you face any issue.

Thanks,
Praneta

>

**Comment by gattur** [comment]
I can see activate file in flaskvenv folder

**Comment by gattur** [comment]
This worked for me
source flaskvenv/bin/activate
is this fine?

**Comment by Praneta-Paithankar** [comment]
Hi,

I would suggest you create and activate a new virtual environment. flaskenv environment might not work on your system.

**Comment by arswaroop** [comment]
Hi Praneta,
Got the below error when i tried to start diet service-

(env) c:\Code\gateway-falcons\diet-service\diet>myfitnesspal store-password "schwenck.live@gmail.com"
Traceback (most recent call last):
  File "C:\Users\arswa\AppData\Local\Programs\Python\Python37-32\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\arswa\AppData\Local\Programs\Python\Python37-32\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Code\gateway-falcons\diet-service\diet\env\Scripts\myfitnesspal.exe\__main__.py", line 5, in <module>
  File "c:\code\gateway-falcons\diet-service\diet\env\lib\site-packages\myfitnesspal\cmdline.py", line 6, in <module>
    from .commands import COMMANDS, get_command_list
  File "c:\code\gateway-falcons\diet-service\diet\env\lib\site-packages\myfitnesspal\commands.py", line 8, in <module>
    from blessed import Terminal
  File "c:\code\gateway-falcons\diet-service\diet\env\lib\site-packages\blessed\__init__.py", line 10, in <module>
    from blessed.terminal import Terminal
  File "c:\code\gateway-falcons\diet-service\diet\env\lib\site-packages\blessed\terminal.py", line 8, in <module>
    import curses
  File "C:\Users\arswa\AppData\Local\Programs\Python\Python37-32\Lib\curses\__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'

**Comment by Praneta-Paithankar** [comment]
@arswaroop 
 I think curses (system python package) is not installed in the windows at the time of compiling Python3 sources.  Try installing pip install windows-curses

**Comment by arswaroop** [comment]
@Praneta-Paithankar Thanks for the reply, that fixed the issue. but got below error while running the python file-

(env) c:\Code\gateway-falcons\diet-service\diet>python dietCron.py
Traceback (most recent call last):
  File "dietCron.py", line 9, in <module>
    cron.write()
  File "c:\Code\gateway-falcons\diet-service\diet\env\lib\site-packages\crontab.py", line 355, in write
    raise IOError("Please specify user or filename to write.")
OSError: Please specify user or filename to write.

(env) c:\Code\gateway-falcons\diet-service\diet>

**Comment by arswaroop** [comment]
Hi @Praneta-Paithankar,
Same error for fitness service-

(env) c:\Code\gateway-falcons\fitness-service\fitness>python fitnessCron.py
Traceback (most recent call last):
  File "fitnessCron.py", line 9, in <module>
    cron.write()
  File "c:\Code\gateway-falcons\fitness-service\fitness\env\lib\site-packages\crontab.py", line 355, in write
    raise IOError("Please specify user or filename to write.")
OSError: Please specify user or filename to write.

(env) c:\Code\gateway-falcons\fitness-service\fitness>

**Comment by Praneta-Paithankar** [comment]
@arswaroop I think commands for creating cron jobs on windows machine are different. I will fix it.  I will get back to you.

**Comment by Praneta-Paithankar** [comment]
@gattur  and @arswaroop 

I have updated cron jobs for windows. I also updated the wiki. Please follow the new instruction to set up python microservices.

**Comment by arswaroop** [comment]
I was able to run the python services. Thanks @Praneta-Paithankar

**Comment by tylerthedeveloper** [comment]
Closing due to inactivity unless @gattur has new issues
