### ISSUE TITLE
Error while starting NodeJs Server

### ISSUE THREAD

**Issue by absheth** [airavata-courses/Gateway-Falcons#20]
```
 2019-02-09 18:35:04  absheth  on  149.160.180.231  ~/course/science-gateway-architecture/peer-review/gateway-falcons/back-end/server
$ npm start

> server@0.0.0 start /Users/absheth/course/science-gateway-architecture/peer-review/gateway-falcons/back-end/server
> node ./bin/www

express-session deprecated req.secret; provide secret option utils/middleware.js:35:11
internal/validators.js:125
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at Object.join (path.js:1147:7)
    at parseFile (/Users/absheth/course/science-gateway-architecture/peer-review/gateway-falcons/back-end/server/utils/json_fileparser.js:4:27)
    at Object.<anonymous> (/Users/absheth/course/science-gateway-architecture/peer-review/gateway-falcons/back-end/server/app.js:14:26)
    at Module._compile (internal/modules/cjs/loader.js:734:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
    at Function.Module._load (internal/modules/cjs/loader.js:558:3)
    at Module.require (internal/modules/cjs/loader.js:663:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/absheth/course/science-gateway-architecture/peer-review/gateway-falcons/back-end/server/bin/www:7:11)
    at Module._compile (internal/modules/cjs/loader.js:734:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! server@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the server@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/absheth/.npm/_logs/2019-02-09T23_35_10_745Z-debug.log
```

**Comment by absheth** [comment]
I think I skipped a step. Let me confirm

**Comment by absheth** [comment]
Not an issue.
